name: Lint
description: Runs lint command

inputs:
  github-personal-access-token:
    description: 'A token used for accessing private NPM packages (published by Flybits Inc.)'
    required: true

  notify-slack-on-failure:
    description: 'Whether to notify a Slack channel if the job fails'
    default: false
    required: false

  slack-bot-token:
    description: 'A bot token to publish a message on Slack'
    required: false

  slack-ts:
    description: 'The timestamp of the Slack message'
    required: false

  web-app-name:
    description: 'A human-readable name of your web application'
    default: ${{ github.event.repository.name }}
    required: false

runs:
  using: 'composite'
  steps:
    - name: Validate Github Actions' inputs
      shell: bash
      run: |
        [[ "${{ inputs.github-personal-access-token }}" ]] || { echo "github-personal-access-token input is empty"; exit 1; }

    - name: Install Node and NPM packages
      uses: flybits/actions/frontend/node-npm/install@main
      with:
        github-personal-access-token: ${{ inputs.github-personal-access-token }}
        slack-bot-token: ${{ inputs.slack-bot-token }}
        web-app-name: ${{ inputs.web-app-name }}

    - name: Run lint
      shell: bash
      run: npm run lint

    - if: ${{ inputs.notify-slack-on-failure == 'true' && failure() }}
      name: Notify Slack
      uses: flybits/actions/frontend/slack/job-failure@main
      with:
        bot-token: ${{ inputs.slack-bot-token }}
        message: '🧐 Linting failed'
        thread-ts: ${{ inputs.slack-ts }}
        web-app-name: ${{ inputs.web-app-name }}
