name: Install Node and NPM packages
description: Installs node and project's packages; restore from cache if possible

inputs:
  github-personal-access-token:
    description: 'A token used for accessing private NPM packages (published by Flybits Inc.)'
    required: true

  node-version:
    description: 'The version of Node to use'
    default: 'lts/*'
    required: false

  slack-bot-token:
    description: 'A bot token to publish a message on Slack'
    required: true

  web-app-name:
    description: 'A human-readable name of your web application'
    default: ${{ github.event.repository.name }}
    required: false

runs:
  using: 'composite'
  steps:
    - name: Validate Github Actions' inputs
      shell: bash
      run: |
        [[ "${{ inputs.github-personal-access-token }}" ]] || { echo "github-personal-access-token input is empty"; exit 1; }
        [[ "${{ inputs.slack-bot-token }}" ]] || { echo "slack-bot-token input is empty"; exit 1; }

    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Restore packages from cache
      id: node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-xnode-modules-${{ hashFiles('yarn.lock') }}

    - name: Generate .npmrc file
      if: steps.node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        NPMRC_FILE=".npmrc"
        rm -f $NPMRC_FILE
        echo "@flybits:registry=https://npm.pkg.github.com" >> $NPMRC_FILE
        echo "https://npm.pkg.github.com/:_authToken=${{ inputs.github-personal-access-token }}" >> $NPMRC_FILE

    - name: Install packages
      if: steps.node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile

    - if: ${{ failure() }}
      name: Notify Slack
      uses: flybits/actions/frontend/slack/job-failure@main
      with:
        bot-token: ${{ inputs.slack-bot-token }}
        message: '😤 Installing Node or NPM packages failed'
        web-app-name: ${{ inputs.web-app-name }}
