name: Install Node and NPM packages
description: Installs node and project's packages; restore from cache if possible

inputs:
  git-ref:
    description: "The branch, tag or SHA to check out."
    required: false

  github-personal-access-token:
    description: "A token used for accessing private NPM packages (published by Flybits Inc.)"
    required: true

  node-version:
    description: "The version of Node to use"
    default: "lts/*"
    required: false

  package-manager:
    description: "The package manager to use ('npm' or 'yarn')"
    default: "yarn"
    required: false

  notify-slack-on-failure:
    description: "Whether to notify a Slack channel if the job fails"
    default: false
    required: false

  slack-bot-token:
    description: "A bot token to publish a message on Slack"
    required: false

  slack-ts:
    description: "The timestamp of the Slack message"
    required: false

  web-app-name:
    description: "A human-readable name of your web application"
    default: ${{ github.event.repository.name }}
    required: false

runs:
  using: "composite"
  steps:
    - name: Validate Github Actions' inputs
      shell: bash
      env:
        GITHUB_PAT: ${{ inputs.github-personal-access-token }}
        PACKAGE_MANAGER: ${{ inputs.package-manager }}
      run: |
        [[ "${GITHUB_PAT}" ]] || { echo "github-personal-access-token input is empty"; exit 1; }
        
        case "${PACKAGE_MANAGER}" in
          npm|yarn) ;;
          *) echo "package-manager input must be 'npm' or 'yarn', got '${PACKAGE_MANAGER}'"; exit 1;;
        esac

    - name: Checkout the repository
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.git-ref }}

    - name: Install Node and setup cache
      uses: actions/setup-node@v6
      with:
        cache: ${{ inputs.package-manager }}
        node-version: ${{ inputs.node-version }}

    - name: Generate .npmrc file
      shell: bash
      env:
        GITHUB_PAT: ${{ inputs.github-personal-access-token }}
      run: |
        NPMRC_FILE=".npmrc"
        rm -f "$NPMRC_FILE"
        echo "@flybits:registry=https://npm.pkg.github.com" >> "$NPMRC_FILE"
        echo "https://npm.pkg.github.com/:_authToken=${GITHUB_PAT}" >> "$NPMRC_FILE"

    - name: Install packages via NPM
      if: ${{ inputs.package-manager == 'npm' }}
      shell: bash
      run: npm ci

    - name: Install packages via Yarn
      if: ${{ inputs.package-manager == 'yarn' }}
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Remove .npmrc file
      if: always()
      shell: bash
      run: rm -f .npmrc

    - name: Notify Slack
      if: ${{ failure() && inputs.notify-slack-on-failure == 'true' }}
      uses: flybits/actions/frontend/slack/job-message@main
      with:
        bot-token: ${{ inputs.slack-bot-token }}
        message: "😤 Installing Node or NPM packages failed"
        thread-ts: ${{ inputs.slack-ts }}
        web-app-name: ${{ inputs.web-app-name }}
