name: Notify failed job via Slack
author: Anker P
description: Send message to Slack when a job fails
inputs:
  SLACK_BOT_TOKEN:
    description: 'Token for the Slack bot'
    required: true

  CHANNEL_ID:
    description: 'Channel ID to send the message to'
    required: true

  UPDATE_TS:
    description: 'Timestamp of the message to update'
    required: true
    default: ''

  JOB_NAME:
    description: 'Name of the job'
    required: true
    default: 'Job'

outputs:
runs:
