name: Test
description: Runs all tests

inputs:
  cypress-spec:
    description: 'A path/glob pattern that will determine which tests should be executed'
    required: false

  flybits-project-environment:
    description: 'The environment in which the Flybits project is created'
    required: true

  flybits-project-jwt:
    description: 'A JSON Web Token to access Experience Studio'
    required: true

  github-personal-access-token:
    description: 'A token used for accessing private repository (created under Flybits Inc. organization)'
    required: true

  notify-slack-on-failure:
    description: 'Whether to notify a Slack channel if the job fails'
    default: false
    required: false

  slack-bot-token:
    description: 'A bot token to publish a message on Slack'
    required: false

  slack-ts:
    description: 'The timestamp of the Slack message'
    required: false

  web-app-name:
    description: 'A human-readable name of your web application'
    default: ${{ github.event.repository.name }}
    required: false

runs:
  using: 'composite'
  steps:
    - name: Validate Github Actions' inputs
      shell: bash
      run: |
        [[ "${{ inputs.flybits-project-environment }}" ]] || { echo "flybits-project-environment input is empty"; exit 1; }
        [[ "${{ inputs.flybits-project-jwt }}" ]] || { echo "flybits-project-jwt input is empty"; exit 1; }
        [[ "${{ inputs.github-personal-access-token }}" ]] || { echo "github-personal-access-token input is empty"; exit 1; }

    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        ref: refs/heads/main
        repository: 'flybits/frontend-cypress'
        token: ${{ inputs.github-personal-access-token }}

    - name: Run Cypress tests
      uses: flybits/actions/frontend/cypress/test@main
      with:
        cypress-spec: ${{ inputs.cypress-spec }}
        flybits-project-environment: ${{ inputs.flybits-project-environment }}
        flybits-project-jwt: ${{ inputs.flybits-project-jwt }}

    - if: ${{ inputs.notify-slack-on-failure == 'true' && failure() }}
      name: Notify Slack
      uses: flybits/actions/frontend/slack/job-failure@main
      with:
        bot-token: ${{ inputs.slack-bot-token }}
        message: '😒 Running Cypress tests failed'
        thread-ts: ${{ inputs.slack-ts }}
        web-app-name: ${{ inputs.web-app-name }}
