name: Verify pull request's title
description: Enforces that the title of a pull request must follow the Conventional Commits format

inputs:
  github-personal-access-token:
    description: 'A token used for accessing private repository (created under Flybits Inc. organization)'
    default: ${{ github.token }}
    required: false

runs:
  using: 'composite'
  steps:
    - name: Validate Github Actions' inputs
      shell: bash
      run: |
        [[ "${{ inputs.github-personal-access-token }}" ]] || { echo "github-personal-access-token input is empty"; exit 1; }

    - name: Verify Conventional Commits' structure
      shell: bash
      run: |
        echo

        function validate() {
          if [[ "$PR_TITLE" =~ $REGEX ]]; then
            echo -e "\t✅ $MESSAGE"
          else
            echo -e "\t❌ $MESSAGE"
            exit 1
          fi
        }

        PR_TITLE="${{ github.event.pull_request.title }}"

        MESSAGE='should start with a lowercase word, except "BREAKING"\n'
        REGEX='^(BREAKING CHANGE|[a-z]+).*$'
        validate

        MESSAGE='should follow the Conventional Commit (https://www.conventionalcommits.org) format\n'
        REGEX='^(BREAKING CHANGE|[a-z]+)(\(.+\))?!?: .+$'
        validate

        MESSAGE='should use one of the following types:\n\tBREAKING CHANGE, build, chore, ci, docs, feat, fix, perf, refactor, release, revert, style, test\n'
        REGEX='^(BREAKING CHANGE|build|chore|ci|docs|feat|fix|perf|refactor|release|revert|style|test)'
        validate

        MESSAGE='should use one of the following scopes:\n\tanalytics, audit-history, content, content-manager, context-rule, deps, deps-dev, experience,\n\tfile-upload, flow-visualizer, location, location-management, maker-cheker, merchant-portal,\n\tnotifications, push, release, rule, rule-builder, schedule, security, security-alert,\n\tsmart-targeting, template-library, zones-and-modules\n'
        REGEX='^([a-zA-Z ]+)(\((analytics|audit\-history|content|content\-manager|context\-rule|deps|deps\-dev|experience|file\-upload|flow\-visualizer|location|location\-management|maker\-cheker|merchant\-portal|notifications|push|release|rule|rule\-builder|schedule|security|security\-alert|smart\-targeting|template\-library|zones\-and\-modules).*\))?!?: .+$'
        validate

        MESSAGE='should use the pipe character with spaces before and after (" | ") to separate\n\tthe scope and Jira ticket number in the pull request title\n'
        REGEX='^([a-zA-Z ]+)(\([a-zA-Z0-9 |-]+\))?!?: .+' # Need to refine this regex to make it more stricter
        validate
