name: ScanFrontend
description: Vulnerability Scanning Service for All Production Frontend Repos
inputs:
  github_token:
    description: A GitHub personal access token with repo scope to access private repositories.
    required: true

  environment:
    description: 'The name of the environment to deploy to'
    type: string
    required: true

  build_runner:
    default: 'nx'
    description: 'The name of the build runner to use'
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    #Checkout
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.github_token }}

    #Install Node
    - name: Install Node and NPM packages
      uses: flybits/frontend-github-actions/node-npm/install@main
      with:
        github-personal-access-token: ${{ inputs.github_token }}

    #Build using NX
    - if: ${{ inputs.build_runner == 'nx' }}
      name: Run build
      shell: bash
      run: npx nx build:${{ inputs.environment }}

    #Build using NPM
    - if: ${{ inputs.build_runner == 'npm' }}
      name: Run build
      shell: bash
      run: npm build:${{ inputs.environment }}

    #Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript

    #Run codeql Analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
