name: Test
description: Runs end-to-end tests

inputs:
  github-personal-access-token:
    description: 'A token used for accessing private repository (created under Flybits Inc. organization)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout the repository
      if: ${{ inputs.github-personal-access-token }}
      uses: actions/checkout@v4
      with:
        ref: refs/heads/main
        repository: 'flybits/frontend-cypress'
        token: ${{ inputs.github-personal-access-token }}
