name: Test
description: Runs end-to-end tests

inputs:
  git-ref:
    default: refs/heads/main
    description: 'The branch, tag or SHA to checkout'
    required: false

  github-personal-access-token:
    description: 'A token used for accessing private repository (created under Flybits Inc. organization)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate Github Actions' inputs
      shell: bash
      run: |
        [[ "${{ inputs.github-personal-access-token }}" ]] || { echo "github-personal-access-token input is empty"; exit 1; }

    - name: Checkout the repository
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.git-ref }}
        repository: 'flybits/frontend-cypress'
        token: ${{ inputs.github-personal-access-token }}
