name: Deployment
author: Joao Carvalho
description: GitHub action for deploy backend services.
inputs:
  github_token:
    description: A GitHub personal access token with repo scope to access private repositories.
    required: true
  branch:
    description: Which branch is running the job
    required: true
  version:
    description: 'Semver type of new version (major / minor / patch)'
    required: true
    type: choice
    options: 
    - patch
    - minor
    - major

runs:
  using: "composite"
  steps:
  - name: Validate branch
    run: |
      if [[ "${{ github.event.inputs.version }}" == "main" || "${{ github.event.inputs.version }}" == "master" ]]; then
        echo "This pipeline is only available for master or main branch!"
        exit 1;
      fi
  - uses: actions/checkout@v3
  - name: Generate versions
    uses: HardNorth/github-version-generate@v1.1.2
    with:
      version-source: file
      version-file: VERSION
      release-version-cut-prerelease: true
      next-version-increment-patch: ${{ contains(github.event.inputs.version, 'patch') }}
      next-version-increment-minor: ${{ contains(github.event.inputs.version, 'minor') }}
      next-version-increment-major: ${{ contains(github.event.inputs.version, 'major') }}
  - name: Setup Git
    shell: bash
    run: |
      git config --local user.email "flybitbot@github.com"
      git config --local user.name "flybitbot"  
  - uses: rickstaa/action-create-tag@v1
    with:
      tag: ${{ env.RELEASE_VERSION }}
      github_token: ${{ github.event.inputs.github_token }}
  - name: Create Release
    shell: bash
    run: gh release create ${{ env.RELEASE_VERSION }} --generate-notes
    env:
      GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
  - name: Update version
    shell: bash
    run: |
      echo "${{ env.NEXT_VERSION }}" > VERSION
      if [ -n "$(git status --porcelain)" ]; then
        git commit -am "Beginning ${{env.NEXT_VERSION}} [skip ci]"
        git push --force
      fi