name: Deployment
author: Petar Kramaric
description: GitHub action for deploying android applications
inputs:
  github_token:
    description: A GitHub personal access token with repo scope to access private repositories.
    required: true
  branch:
    description: Which branch is running the job
    required: true
    type: choice
    options:
      - main
  version:
    description: "Semver type of new version (major / minor / patch)"
    required: true
    type: choice
    options:
      - patch
      - minor
      - major
  who_trigger:
    description: "Who trigger the pipeline"
    required: true

runs:
  using: "composite"
  steps:

    #Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    #SETUP GIT LOCAL USER
    - name: Setup Git
      shell: bash
      run: |
        git config user.name "${{ inputs.who_trigger }}"
        git config user.email "${{ inputs.who_trigger }}"
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    #Increase Version Name NON-PATCH
    - name: Bump version major-minor
      uses: HardNorth/github-version-generate@v1.4.0
      if: inputs.version != 'patch'
      with:
        version-source: file
        version-file: VERSION
        release-version-cut-prerelease: true
        next-version-increment-patch: true
        next-version-increment-minor: ${{ contains(inputs.version, 'minor') }}
        next-version-increment-major: ${{ contains(inputs.version, 'major') }}

    #UPDATE Version Name NON-PATCH
    - name: Update version
      shell: bash
      if: inputs.version != 'patch'
      run: |
        echo "${{ env.NEXT_VERSION }}" > VERSION

    #Increase Version Name PATCH
    - name: Generate versions
      uses: HardNorth/github-version-generate@v1.4.0
      with:
        version-source: file
        version-file: VERSION
        release-version-cut-prerelease: true
        next-version-increment-patch: true
        next-version-increment-minor: false
        next-version-increment-major: false

    #Increase Version in Build.gradle file
    - name: Increase version code and change version name
      shell: bash
      run: |
        echo "${{ env.RELEASE_VERSION }}" > VERSION
        current_version_code=$(cat VERSION_CODE)
        echo Version Code: $current_version_code
        echo Version Name: ${{ env.RELEASE_VERSION }}

        sed -i "s/versionCode [0-9]*/versionCode $current_version_code/g" app/build.gradle
        sed -i "s/versionName \"[^\"]*\"/versionName \"${{ env.RELEASE_VERSION }}\"/g" app/build.gradle
        current_version_code=$((current_version_code+1))
        echo "$current_version_code" > VERSION_CODE
        echo "${{ env.NEXT_VERSION }}" > VERSION
    
    #Commit Version Increase Code
    - name: Commit and push changes
      shell: bash
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git diff
          git commit -am "Releasing ${{env.RELEASE_VERSION}}"
          git push --force
        fi
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    #Create Release Tag
    - name: Create Release
      shell: bash
      run: gh release create "v${{ env.RELEASE_VERSION }}" --generate-notes
      env:
        GH_TOKEN: ${{ inputs.github_token }}