name: 'Notify Slack'
description: 'Publishes a message to Slack when a deploy workflow starts'

inputs:
  bot-token:
    description: 'The bot token to use for posting to Slack'
    required: true

  channel-id:
    description: 'The Slack channel to post the message to'
    default: 'C9YA9JUKG'
    required: false

  environment:
    description: 'The name of the environment'
    default: 'Not Specified'
    required: false

  web-app-name:
    description: 'The name of your web application'
    default: ${{ github.event.repository.name }}
    required: false

outputs:
  ts:
    description: 'The timestamp of the Slack message'
    value: ${{ steps.notify-slack.outputs.ts }}

runs:
  using: 'composite'
  steps:
    - name: Validate Github Actions' inputs
      shell: bash
      run: |
        [[ "${{ inputs.bot-token }}" ]] || { echo "bot-token input is empty"; exit 1; }

    - name: Notify Slack
      id: notify-slack
      uses: slackapi/slack-github-action@v2.1.1
      with:
        errors: true
        method: chat.postMessage
        payload: |
          channel: ${{ inputs.channel-id }}
          text: "Deploying *<${{ github.event.repository.html_url }}|${{ inputs.web-app-name }}>* to  *${{ inputs.environment }}* environment"
          blocks:
            - type: "header"
              text:
                type: "plain_text"
                text: "Deployment Alert :rocket:"
            - type: "context"
              elements:
                - type: "image"
                  image_url: "https://github.com/${{ github.triggering_actor }}.png"
                  alt_text: "${{ github.triggering_actor }}"
                - type: "plain_text"
                  emoji: true
                  text: "Triggered by ${{ github.triggering_actor }}"
            - type: "divider"
            - type: "section"
              text:
                type: "mrkdwn"
                text: "Deploying *<${{ github.event.repository.html_url }}|${{ inputs.web-app-name }}>* to  *${{ inputs.environment }}* environment"
              accessory:
                type: "button"
                text:
                  type: "plain_text"
                  text: "Workflow Run"
                  emoji: true
                url: "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
                action_id: "button-action"
            - type: "section"
              text:
                type: "mrkdwn"
                text: "*Branch:* `${{ github.ref_name }}`"
              accessory:
                type: "button"
                text:
                  type: "plain_text"
                  text: "Commit"
                  emoji: true
                url: "${{ github.event.repository.html_url }}"
                action_id: "button-action"
            - type: "context"
              elements:
                - type: "plain_text"
                  text: "*This message will be replaced by the final workflow status."
        token: ${{ inputs.bot-token }}
