name: Govulncheck
author: Petar Kramaric
description: GitHub action for running govulncheck
inputs:
  slack_webhook_url:
    description: A Slack webhook url for alerting on failures
    required: false
  deployment_token:
    description: A deployment token for github
    required: true
  branch:
    description: The branch to run this govulncheck on
    required: true
  show_success_slack_msg:
    description: indicates that all failures and successes should be displayed in slack, otherwise only failures will appear
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{inputs.branch}}
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        go-version: '1.21.3'
    - name: Configure git for private modules
      run: git config --global url."https://${{inputs.deployment_token}}@github.com".insteadOf "https://github.com"
      shell: bash
    - name: Run Go version
      run: go version
      shell: bash
    - name: Get official govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash
    - name: Run govulncheck
      run: govulncheck ./...
      shell: bash
    - name: Send data to Slack If Failure
      if: inputs.slack_webhook_url != '' && failure()
      uses: slackapi/slack-github-action@v1.24.0
      id: slack-failure
      with:
        payload: |
          {
            "attachments": [
              {
                "fallback": "${{ github.repository }} Govulncheck nightly failed",
                "color": "FF0000",
                "author_name": "${{ github.repository }}",
                "author_icon": "https://avatars.slack-edge.com/2023-11-06/6153795552370_f0926dce057ace056b53_96.webp",
                "title": "Nightly Failure",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "fields": [
                  {
                    "title": "Priority",
                    "value": "High",
                    "short": false
                  }
                ],
                "footer": "GitHub Nightly Build for ${{ github.repository }}",
                "footer_icon": "https://github.githubassets.com/favicons/favicon.png"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    - name: Send data to Slack If Success
      if: inputs.slack_webhook_url != '' && !failure() && show_success_slack_msg == 'true'
      uses: slackapi/slack-github-action@v1.24.0
      id: slack-success
      with:
        payload: |
          {
            "attachments": [
              {
                "fallback": "${{ github.repository }} Govulncheck nightly success",
                "color": "008000",
                "author_name": "${{ github.repository }}",
                "author_icon": "https://avatars.slack-edge.com/2023-11-06/6153795552370_f0926dce057ace056b53_96.webp",
                "title": "Nightly Success",
                "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "footer": "GitHub Nightly Build for ${{ github.repository }}",
                "footer_icon": "https://github.githubassets.com/favicons/favicon.png"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      