name: Go gRPC
on:
  push:
    paths:
      - 'go-grpc/**'
jobs:
  go-grpc:
    name: Test go-grpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Go gRPC
        uses: ./go-grpc
        with:
          path: ./go-grpc/test
          command: protoc --proto_path=. --go_out=paths=source_relative,plugins=grpc:. hello.proto
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./go-grpc/test/hello.pb.go
